snippets without selection, complete vim impl

diff --git a/scripts/qsh b/scripts/qsh
--- a/scripts/qsh
+++ b/scripts/qsh
@@ -165,20 +165,46 @@ if [[ -f "$EDITOR_PANE" ]]; then
   fi;
 
   case $OPERATION_TYPE in
-    sql)
+    $OPERATION_TYPE_SQL)
       # Default processing, nothing to do
       ;;
 
-    *query)
+    $OPERATION_TYPE_QUERY)
       # Figure out the script to be called and it's parameters
       QUERY_SCRIPT=$(echo "$2" | awk -F " " '{ print $1; }');
       SCRIPT_PARAMETERS=$(echo "$2" | awk -F " " '{ $1=""; print $0; }');
 
       # Locate the client query script to call
       QSH_QUERY_SCRIPT=$QSH_BASE/clients/$QSH_SQL_CLIENT/$OPERATION_TYPE/$QUERY_SCRIPT;
+      if [[ ! -f "$QSH_QUERY_SCRIPT" ]]; then
+        echo "Invalid query script '$RESULT_QUERY_SCRIPT'";
+        exit -1;
+      fi;
 
       # Allow the client script to process the query to be executed
       "$QSH_QUERY_SCRIPT" "$QSH_EXECUTE_QUERY" "$SCRIPT_PARAMETERS";
+      if [[ $? -ne 0 ]]; then
+        exit -1;
+      fi;
+      ;;
+
+    $OPERATION_TYPE_RESULT_QUERY)
+      # Figure out the script to be called and it's parameters
+      RESULT_QUERY_SCRIPT=$(echo "$2" | sed 's/\([^( ]\+\)[[:space:]]*(\(.*\))/\1/g');
+      SCRIPT_PARAMETERS=$(echo "$2" | sed 's/[^( ]\+[[:space:]]*(\(.*\))/\1/g');
+
+      # Locate the client query script to call
+      QSH_QUERY_SCRIPT=$QSH_BASE/clients/$QSH_SQL_CLIENT/$OPERATION_TYPE/$RESULT_QUERY_SCRIPT;
+      if [[ ! -f "$QSH_QUERY_SCRIPT" ]]; then
+        echo "Invalid result query script '$RESULT_QUERY_SCRIPT'";
+        exit -1;
+      fi;
+
+      # Allow the client script to process the query to be executed
+      "$QSH_QUERY_SCRIPT" "$QSH_EXECUTE_QUERY" "$SCRIPT_PARAMETERS";
+      if [[ $? -ne 0 ]]; then
+        exit -1;
+      fi;
       ;;
   esac
 
