scripts & snippets search paths; better script error reporting in vim

diff --git a/scripts/qsh b/scripts/qsh
--- a/scripts/qsh
+++ b/scripts/qsh
@@ -6,6 +6,8 @@ QSH_BASE="$QSH_SCRIPTS/.."
 # Store some basic information about our execution environment
 QSH=$BASH_SOURCE
 QSH_PAGER_COMMAND="$QSH_SCRIPTS/qsh-pager"
+
+# Other environment details
 WINDOW_ID=$(tmux display-message -p '#I')
 PANE_ID=$(tmux display-message -p '#{pane_id}')
 PID=$$
@@ -102,6 +104,8 @@ export QSH='$QSH' \
        QSH_SWITCH_ON_EXECUTE='$QSH_SWITCH_ON_EXECUTE' \
        QSH_EXECUTE_DELAY='$QSH_EXECUTE_DELAY' \
        QSH_SQL_CLIENT='$QSH_SQL_CLIENT' \
+       QSH_SCRIPTS_PATH='$QSH_SCRIPTS_PATH' \
+       QSH_SNIPPETS_PATH='$QSH_SNIPPETS_PATH' \
        EDITOR_PANE_ID=$(tmux display-message -p '#{pane_id}');
 
 "$QSH_EDITOR" "$EDITOR_FILE";
@@ -214,12 +218,20 @@ if [[ -f "$EDITOR_PANE" ]]; then
       # Figure out the script to be called and it's parameters
       QUERY_SCRIPT=$(echo "$2" | awk -F " " '{ print $1; }');
       SCRIPT_PARAMETERS=$(echo "$2" | awk -F " " '{ $1=""; print $0; }');
+      SCRIPT_TYPE=script
+
+      # Set the search path
+      QSH_SEARCH_PATH=$QSH_SCRIPTS_PATH;
       ;;
 
     $OPERATION_TYPE_SNIPPET)
       # Figure out the script to be called and it's parameters
       QUERY_SCRIPT=$(echo "$2" | sed 's/\([^( ]\+\)[[:space:]]*(\(.*\))/\1/g');
       SCRIPT_PARAMETERS=$(echo "$2" | sed 's/[^( ]\+[[:space:]]*(\(.*\))/\1/g');
+      SCRIPT_TYPE=snippet
+
+      # Set the search path
+      QSH_SEARCH_PATH=$QSH_SNIPPETS_PATH;
 
       # Copy in other files if they exist
       [[ -f "$QSH_EXECUTE_QUERY" ]] && cp "$QSH_EXECUTE_QUERY" "$RESULT_REQUEST_CONTEXT";
@@ -230,10 +242,13 @@ if [[ -f "$EDITOR_PANE" ]]; then
   # If we are running a script or a snippet, make sure the requested script exists
   if [ "$OPERATION_TYPE" == "$OPERATION_TYPE_SCRIPT" ] || \
      [ "$OPERATION_TYPE" == "$OPERATION_TYPE_SNIPPET" ]; then
-    # Locate the client query script to call
-    QSH_QUERY_SCRIPT=$QSH_BASE/clients/$QSH_SQL_CLIENT/$OPERATION_TYPE/$QUERY_SCRIPT;
-    if [[ ! -f "$QSH_QUERY_SCRIPT" ]]; then
-      echo "Invalid script '$QUERY_SCRIPT'";
+    # Locate the client query script/snippet to call
+    QSH_SEARCH_PATH=$QSH_SEARCH_PATH:$QSH_BASE/clients/$QSH_SQL_CLIENT/$OPERATION_TYPE;
+    WHICH=$(which which);
+
+    QSH_QUERY_SCRIPT="$(PATH="$QSH_SEARCH_PATH" "$WHICH" "$QUERY_SCRIPT" 2>&1)";
+    if [[ $? -ne 0 ]]; then
+      echo "Invalid $SCRIPT_TYPE \"$QUERY_SCRIPT\"";
       exit -1;
     fi;
   fi;
